name: Text From Image CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 1.8
      
      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build
        
      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test

      # Run Tests Build
      - name: Upload APK
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
        
        
        
